"""增加拼音的 name 字段

Revision ID: 06d0a101ef2e
Revises: 179bfd31bc27
Create Date: 2025-12-17 17:52:47.275283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d0a101ef2e'
down_revision: Union[str, None] = '179bfd31bc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'operator_id',
               existing_type=sa.VARCHAR(length=100),
               comment='操作人ID',
               existing_nullable=True)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.VARCHAR(length=100),
               comment='目标ID',
               existing_nullable=True)
    op.alter_column('resource_bindings', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment='创建人ID',
               existing_nullable=True)
    op.create_index('idx_user_namespace', 'resource_bindings', ['user_id', 'namespace'], unique=False)
    op.create_index(op.f('ix_resource_bindings_user_id'), 'resource_bindings', ['user_id'], unique=False)
    op.alter_column('user_roles', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment='分配人ID',
               existing_nullable=True)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.add_column('users', sa.Column('name', sa.String(length=30), nullable=True, comment='用户拼音'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.alter_column('user_roles', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='分配人ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_resource_bindings_user_id'), table_name='resource_bindings')
    op.drop_index('idx_user_namespace', table_name='resource_bindings')
    op.alter_column('resource_bindings', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='目标ID',
               existing_nullable=True)
    op.alter_column('audit_logs', 'operator_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='操作人ID',
               existing_nullable=True)
    # ### end Alembic commands ###

