"""Initial migration

Revision ID: 836823124d94
Revises: 
Create Date: 2025-11-15 23:27:49.950395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836823124d94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='系统代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='系统名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='系统描述'),
    sa.Column('api_endpoint', sa.String(length=200), nullable=True, comment='系统API地址'),
    sa.Column('system_token', sa.String(length=1000), nullable=True, comment='系统Token'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active, inactive'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_token')
    )
    op.create_index(op.f('ix_systems_code'), 'systems', ['code'], unique=True)
    op.create_index(op.f('ix_systems_id'), 'systems', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feishu_user_id', sa.String(length=100), nullable=False, comment='飞书用户ID'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=200), nullable=True, comment='邮箱'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('mobile', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('dept_ids', sa.JSON(), nullable=True, comment='部门ID列表'),
    sa.Column('dept_names', sa.JSON(), nullable=True, comment='部门名称列表'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active, inactive'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_feishu_user_id'), 'users', ['feishu_user_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='操作类型: role_created, permission_updated'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='目标类型: role, permission, user'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='目标ID'),
    sa.Column('namespace', sa.String(length=50), nullable=True, comment='命名空间'),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True, comment='变更详情'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User Agent'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_namespace'), 'audit_logs', ['namespace'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限代码: system_a:document:read'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('namespace', sa.String(length=50), nullable=False, comment='命名空间'),
    sa.Column('system_id', sa.Integer(), nullable=True, comment='所属系统ID'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型: document, order'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='操作: read, write, delete'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_namespace'), 'permissions', ['namespace'], unique=False)
    op.create_table('resource_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=50), nullable=False, comment='命名空间: global, system_a'),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型: project, team, document'),
    sa.Column('resource_id', sa.String(length=100), nullable=False, comment='资源ID'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='操作: read, write, admin'),
    sa.Column('extended_metadata', sa.JSON(), nullable=True, comment='扩展字段'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resource', 'resource_bindings', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_user_namespace', 'resource_bindings', ['user_id', 'namespace'], unique=False)
    op.create_index(op.f('ix_resource_bindings_id'), 'resource_bindings', ['id'], unique=False)
    op.create_index(op.f('ix_resource_bindings_namespace'), 'resource_bindings', ['namespace'], unique=False)
    op.create_index(op.f('ix_resource_bindings_user_id'), 'resource_bindings', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='角色代码: global:admin, system_a:editor'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('namespace', sa.String(length=50), nullable=False, comment='命名空间: global, system_a'),
    sa.Column('system_id', sa.Integer(), nullable=True, comment='所属系统ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('is_system_role', sa.Boolean(), nullable=True, comment='是否系统角色'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_namespace_code', 'roles', ['namespace', 'code'], unique=False)
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_namespace'), 'roles', ['namespace'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('route_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False, comment='路由正则: /api/v1/documents/\\d+'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='HTTP方法: GET, POST, *'),
    sa.Column('description', sa.Text(), nullable=True, comment='规则描述'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级(数字越大优先级越高)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_patterns_id'), 'route_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_route_patterns_role_id'), 'route_patterns', ['role_id'], unique=False)
    op.create_index(op.f('ix_route_patterns_system_id'), 'route_patterns', ['system_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='分配人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_route_patterns_system_id'), table_name='route_patterns')
    op.drop_index(op.f('ix_route_patterns_role_id'), table_name='route_patterns')
    op.drop_index(op.f('ix_route_patterns_id'), table_name='route_patterns')
    op.drop_table('route_patterns')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_namespace'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_index('idx_namespace_code', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resource_bindings_user_id'), table_name='resource_bindings')
    op.drop_index(op.f('ix_resource_bindings_namespace'), table_name='resource_bindings')
    op.drop_index(op.f('ix_resource_bindings_id'), table_name='resource_bindings')
    op.drop_index('idx_user_namespace', table_name='resource_bindings')
    op.drop_index('idx_resource', table_name='resource_bindings')
    op.drop_table('resource_bindings')
    op.drop_index(op.f('ix_permissions_namespace'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_audit_logs_namespace'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_feishu_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_systems_id'), table_name='systems')
    op.drop_index(op.f('ix_systems_code'), table_name='systems')
    op.drop_table('systems')
    # ### end Alembic commands ###

